if [[ -s "$HOME/.adrian.alias" ]]; then
  source "$HOME/.adrian.alias"
fi

if [[ -s "$HOME/.adrian.function" ]]; then
  source "$HOME/.adrian.function"
fi

if [[ -s "$HOME/.adrian.env" ]]; then
  source "$HOME/.adrian.env"
fi

if [[ -s "$HOME/.adrian.rc" ]]; then
  source "$HOME/.adrian.rc"
fi
